sudo: false
addons:
  apt_packages:
  - lib32stdc++6
env:
  global:
  - INCLUDE=addons/sourcemod/scripting/include/
  - SCRIPTING=addons/sourcemod/scripting/
  - PLUGINS=addons/sourcemod/plugins/
  matrix:
  - SOURCEMOD=1.8
before_install:
- mkdir build-env
install:
- cd build-env
- wget -q "http://www.sourcemod.net/latest.php?version=1.8&os=linux" -O sourcemod.tar.gz
- tar -xzvf sourcemod.tar.gz
- cd ../
- find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
- cp -rv addons/sourcemod/scripting/. build-env/addons/sourcemod/scripting/
- cp -rv addons/sourcemod/scripting/include/. build-env/addons/sourcemod/scripting/include/
before_script:
- chmod +rx build-env/addons/sourcemod/scripting/spcomp
- chmod +rx build-env/addons/sourcemod/scripting/compile.sh
- cd build-env/addons/sourcemod/scripting/
script:
- "./compile.sh"
after_success:
- cd ../../../..
- cp -rv build-env/addons/sourcemod/scripting/compiled/. $PLUGINS
- ls
- chmod +x discord.sh
- ./discord.sh success
after_failure:
- chmod +x discord.sh
- ./discord.sh failure
deploy:
  provider: releases
  api_key:
    secure: H5SbyA91GFN7DcDWZDY0pqNTEBWuXyDe/LlzGlkKu9zZzf8rretfMKTPHHqLjF6SRZ1brrk1qG4iFLq08eWA/FaP/uHgDHZj1l1kkY57ftit80RlrGUnDodSJzl5Qne6rSQ721Dueq5jDO+WjZ8qFegN0QJJUziSeYRM5ex1+uPMFip6lvW5Er5SeRRHV7044CY/nk37PAQvGoxtULnCxaV8Tn3ZzdCIUroLyRf5c46v7iRoNgbVvYzSEyaNpDaHaiWaFXUU5+gK+IVE64FheLHHEp5wosatGV63sL/9auRgi3UX8udfs/w1rVQUFkH0HCqYE8EiOuZERV3160IGGIbJCXz+U9GVzVuMFvnUEX6fh0qdhuURV1rlg/VHG2S1TSM2cUAGO6+Dqhlg/Z2j9PkJ+O0eBQXfSrrPColIWTehAIWEQVhNG34hj0RAP0uVGr1A+DaOMNIdDCKHrjKt1SSD4nnZvi8ozIlZpXtgtnl+Y4OLNiB/w9edsNdow7UpcDdU4JvJgAzsWKPyJWCAtug7CM4q4WaZzJfVMYdT+sv3vrt3gy6pDexM8o2HVyI+Z/b7k8L3+b0vjlFnp0+pMAC+5l6eDNL2kMcBDRBlJooVvag36EWNFoCFGQYyEiMWEoTm36npGIkLTH3x6djVDS0dD5p4JbivmVgJN+yimEg=
  file: build-env/addon/sourcemod/scripting/compiled/gamedaemon.smx
  skip_cleanup: true
  on:
    repo: clani90/sm-gamedaemon
    tags: true
notifications:
  email: false
